services:
  - type: web
    name: quizverse
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: openai/gpt-oss-20b
      - key: GROQ_BASE_URL
        value: https://api.groq.com/openai/v1
      - key: QUIZVERSE_SECRET
        generateValue: true
